{% set name = "literalai" %}
{% set version = "0.1.201" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29e4ccadd9d68bfea319a7f0b4fc32611b081990d9195f98e5e97a14d24d3713

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # traceloop-sdk start support python from the version 3.10
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - packaging >=23.0
    - httpx >=0.23.0
    - pydantic >=1,<3
    - chevron >=0.14.0
    - traceloop-sdk >=0.33.12

# E   Exception: LITERAL_API_KEY not set
{% set deselect_tests = " --deselect=tests/unit/test_cache.py::test_put_and_get_prompt_by_id_by_name_version_by_name" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_cache.py::test_clear_cache" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/unit/test_cache.py::test_update_existing_prompt" %}
test:
  source_files:
    - tests
  imports:
    - literalai
    - literalai.api
    - literalai.api.asynchronous
    - literalai.api.base
    - literalai.api.helpers
    - literalai.api.helpers
    - literalai.api.synchronous
    - literalai.cache.prompt_helpers
    - literalai.cache.shared_cache
    - literalai.callback.langchain_callback
    - literalai.callback.openai_agents_processor
    - literalai.client
    - literalai.context
    - literalai.environment
    - literalai.evaluation.dataset
    - literalai.evaluation.dataset_experiment
    - literalai.evaluation.dataset_item
    - literalai.evaluation.experiment_item_run
    - literalai.event_processor
    - literalai.exporter
    - literalai.helper
    - literalai.instrumentation
    - literalai.my_types
    - literalai.observability.filter
    - literalai.observability.generation
    - literalai.observability.message
    - literalai.observability.step
    - literalai.observability.thread
    - literalai.prompt_engineering.prompt
    - literalai.requirements
    - literalai.version
    - literalai.wrappers
  commands:
    - pip check
    - pytest -v tests {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://github.com/Chainlit
  summary: An SDK for observability in Python applications
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://docs.literalai.com/python-client/get-started/introduction
  dev_url: https://github.com/Chainlit/literalai-python
  description: |
    Chainlit is a great tool for building internal and external AI chatbots and copilots. 
    Were very thankful for the community that has built on top of it.
    In 2024, we also built Literal AI, an LLMOps product. Both products achieved notable milestones:
      Chainlit: Used by Stability AI, Microsoft, Nvidia and many others
      Literal AI: Adopted by various companies for LLM observability
    However, despite enabling great AI projects, we werent able to differentiate enough in these competitive markets to build sustainable revenue.

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for chainlit
  recipe-maintainers:
    - ianaobi
